### PR TITLE
fix: address 7 GitHub issues — normalization, truncation, ranking features, UX

### LINKED ISSUE #5: add github link

### LINKED ISSUE #16: masthead text
something that explains the name.

slug.social

slugs 
  * leave trails (full history of consensus is availible)
  * are slow and deliberate (thinking is encouraged, in contrast to currently popular platforms)

in programming slugs, popularized by python's django, are url-safe pieces of text. these are all over slug.social, they are the primary battleground. the slug is the location.

in linotype printing, slugs are the pieces of metal that imprint the words. word made flesh.

### LINKED ISSUE #67: Fix ranking normalization
> The one thing I notice you didn't do is his pairwise normalization step — a_ij = A_ij / (A_ij + A_ji) — before running the power iteration. In apply_vote you're accumulating raw weights into the edge map with +=. Eric specifically flagged that if the same pair gets voted on more than once, you need that normalization or the scores get skewed by how many times a pair was compared rather than the aggregate preference. At your current scale it might not matter much, but it will.

+How does this interact with plutocratic votes ..

### LINKED ISSUE #68: Truncate large post bodies with 'show full' link (JSON/CLI/HTML)
## Problem

A thread post with a 400kb JSON blob as the body breaks everything — slow to load, unusable in the CLI, wrecks HTML layout.

## Solution

Add a character limit to post bodies in all three surfaces, with a way to access the full content:

**JSON API** (`GET /api/v0/thread`): truncate `body` at N chars, add a `truncated: true` field and a `post_url` or `post_id` the client can use to fetch the full post via `?post_id=...`.

**CLI** (`forum <thread>`): truncate displayed body, print something like `[truncated — run: slugsocial forum <thread> --post <id>]` to get the full post.

**HTML** (`/t/:tag`): truncate with a `show full ↓` anchor/link to the permalink (`/t/:tag/:index`), which renders the full post.

## Details

- Suggested limit: ~2000 chars for display, configurable or hardcoded
- The full post is always available via the existing `?post_id=` and `/t/:tag/:index` endpoints — no new storage needed
- Ingest-time size limit is a separate question (probably worth a separate issue)

### LINKED ISSUE #70: garden children --depth
Image

### LINKED ISSUE #71: index root is not sorted
this is like the entry point to the lightmode, lightmode's entire point is that its sorted by vote

### LINKED ISSUE #72: Global ranking with pagination and percent option
## Feature

Add a way to see the **global ranking** across all items, with pagination and an optional percent display.

## API

\`GET /api/v0/rank?path=~&limit=N&offset=N\`

- \`limit\` — max items to return (default: 50)
- \`offset\` — skip first N results (default: 0)
- \`percent\` — if true, include normalized percent score (0–100) alongside raw score

## CLI

\`\`\`bash
npx slugsocial garden rank [--limit N] [--offset N] [--percent] [--json]
\`\`\`

Or extend the existing \`garden children\` / \`garden tree\` commands.

## Notes

- Global rank = rank across all leaf items regardless of scope/parent
- Percent: normalize scores so the top item = 100%, lowest = 0%
- Should support \`--json\` flag like other CLI commands

### PR DESCRIPTION
**Pull request by tr1n1tycat**
## Summary

This PR addresses 7 open issues in one coherent batch, ordered from correctness fixes to features to zero-risk UX improvements.

Closes #67
Closes #68
Closes #70
Closes #71
Closes #72
Closes #5
Closes #16

---

## #67 — Fix ranking normalization

**Problem:** `compute_scores_from_edges` fed raw accumulated weights directly into the power-iteration matrix. Pairs voted on repeatedly gained disproportionate influence over pairs voted on once, regardless of which direction the preference pointed.

**Fix:** Pairwise normalization step added before building the transition matrix:

```
a_ij = A_ij / (A_ij + A_ji)
```

Raw weights still accumulate in the reducer (useful for auditing). Normalization happens only at ranking time, leaving the storage layer unchanged.

**Test added** (`server/tests/basic.rs::ranking_repeated_votes_normalized`): voting A>B at 3:1 three times must produce identical scores to voting 3:1 once. The test asserts both winner order and score equality within 1e-6.

---

## #68 — Truncate large post bodies

No truncation anywhere in the pipeline meant a 400 KB post body broke all three surfaces. Fixed across the board:

| Surface | Change |
|---------|--------|
| **API** (`server/src/api.rs`) | `get_thread` caps body at 2000 chars, sets `truncated: bool`. New `post_id` query param bypasses truncation for a single post. `PostRow` now carries `id` and `actor`. |
| **HTML** (`server/src/html/forum.rs`) | Truncated posts show a `[show full post]` link to `/t/:tag/:id`. New `thread_post_view` handler at that route renders the full post. Route registered in `server/src/lib.rs`. |
| **CLI** (`cli/src/main.rs`) | Truncated posts print `[truncated — run with --post <id> to see full]`. New `--post <ID>` flag fetches the single post untruncated. |

`PostRow` changes in `types/src/lib.rs` are additive (new fields, nothing removed) — no breaking change to existing API consumers.

---

## #70 — `garden children --depth`

`resolve_scope_recursive` added to `server/src/scope_rank.rs`. Given a depth N, it BFS-collects children up to N levels deep, then passes the full item set to `build_rankings_for_item_set`. New `depth` query param on `/api/v0/rank`; default 1 preserves existing behavior exactly.

CLI: `garden children <path> --depth N`.

---

## #71 — Root index sorted by votes

`garden_index` previously sorted alphabetically. Now calls `build_children_rankings(&reduced, "")` — the same function the API's `get_rank` calls when no parent is specified, and the same function every other ontology page uses for its child list. Ranked components render as `<ol>`; unranked items render as `<ul>` below them, matching the existing `render_scope_view` pattern.

---

## #72 — Global ranking with pagination and percent

`/api/v0/rank?parent=~` now collects all items from `reduced.items` and ranks the full set. New query params:

- `offset=N` — skip first N items (pagination)
- `percent=true` — include each item's score as % of the top score in its component
- `limit` was already parsed but never applied — now wired up via `paginate_rankings`

`RankRow` gains an optional `percent: Option<f64>` field, omitted from JSON when null (`skip_serializing_if`).

CLI: new `garden rank` subcommand with `--limit`, `--offset`, `--percent`, `--json`. Display numbering respects offset so `--offset 20 --limit 20` prints items 21–40.

---

## #5 — GitHub link

Single line added to the `#controls` div in `server/src/html/mod.rs`:

```html
<a href="https://github.com/sortersocial/slug" id="src-link">src</a>
```

---

## #16 — Masthead text

`<details id="slug-masthead">` element added to the layout footer. Summary: "slug?". Expanded body covers the four etymologies from the issue:

> slugs leave trails — full history preserved. slugs are slow and deliberate — thinking encouraged. programming slugs — url-safe readable text. linotype slugs — the word made metal, made flesh.

Collapsible so it doesn't clutter the default view.

---

## Files changed

| File | Issues |
|------|--------|
| `server/src/html/mod.rs` | #5, #16 |
| `server/src/html/garden.rs` | #71 |
| `server/src/html/forum.rs` | #68 |
| `server/src/lib.rs` | #68 (new route) |
| `server/src/ranking.rs` | #67 |
| `server/src/scope_rank.rs` | #70 |
| `server/src/api.rs` | #68, #72, #70 |
| `server/tests/basic.rs` | #67 |
| `types/src/lib.rs` | #68, #72 |
| `cli/src/main.rs` | #68, #70, #72 |

## Test plan

- [ ] `cargo test` passes (including new `ranking_repeated_votes_normalized`)
- [ ] Post a message > 2000 chars; verify truncation + "show full post" link works
- [ ] `npx slugsocial forum <thread> --post <id>` returns full body
- [ ] `/~` root page shows items in vote order, not alphabetically
- [ ] `npx slugsocial garden rank --percent` returns numbered global ranking
- [ ] `npx slugsocial garden children <path> --depth 2` returns grandchildren
- [ ] GitHub "src" link appears in controls
- [ ] "slug?" footer details expand correctly

Made with [Cursor](https://cursor.com)

### CODE REVIEW

File: server/src/html/forum.rs [hunk 1]
```diff
@@ -94,200 +186,117 @@ pub async fn index(State(state): State<AppState>) -> impl IntoResponse {
...
-            (cli_panel(&format!("npx slugsocial forum {tag}")))
+            (render_ingest_form())
+            (render_thread_presence_script())
+        },
+    );
+    Html(page.into_string()).into_response()
+}
+
+/// Single-post view — `/t/:tag/:id` — shows one ingest at full length.
+pub async fn thread_post_view(
```
Comment (tommy-mor) [inline server/src/html/forum.rs]: this is already implemented in main.

https://slug.social/t/fullstack/0

remove it from this pr plox

File: server/src/html/garden.rs [hunk 2]
```diff
@@ -27,81 +27,63 @@ fn item_href(item: &str) -> String {
...
-                    .map(|path| {
-                        let children = reduced.item_children.get(path).map(|c| c.len()).unwrap_or(0);
-                        (path.clone(), children)
-                    })
-                    .collect()
-            })
-            .unwrap_or_default();
-        v.sort_by(|a, b| a.0.cmp(&b.0));
-        v
+        build_children_rankings(&reduced, "")
```
Comment (tommy-mor) [inline server/src/html/garden.rs]: nice

File: server/src/html/mod.rs [hunk 3]
```diff
@@ -52,18 +50,24 @@ pub(super) fn layout(title: &str, view: &str, body: Markup, views: Option<u64>)
                 script src="https://unpkg.com/idiomorph@0.3.0/dist/idiomorph.min.js" {}
             }
             body class=(view) {
-                @if let Some(n) = views {
-                    span class="view-meta muted" { " · " (n) " views" }
-                }
                 (body)
                 div id="controls" {
+                    a href="https://github.com/sortersocial/slug" id="src-link" { "src" }
```
Comment (tommy-mor) [inline server/src/html/mod.rs]: i was thinking moreso like this. 

https://github.com/sortersocial/index/blob/main/src/templates/_github_corner.html

a little corner cat. sorry i didn't specify earlier

File: server/src/api.rs [hunk 4]
```diff
@@ -361,14 +268,20 @@ pub fn validate_ingest_document(
...
     pub limit: Option<usize>,
+    /// Skip the first N items (for pagination).
     #[serde(default)]
-    pub actor: Option<String>,
+    pub offset: Option<usize>,
+    /// When true, each RankRow includes a `percent` field: score as % of max score in its component.
+    #[serde(default)]
+    pub percent: Option<bool>,
+    /// How many levels deep to resolve children (default 1 = direct children only).
     #[serde(default)]
```
Comment (tommy-mor) [inline server/src/api.rs]: should error somewhere if you try to do --depth and --global at the same time

also does --percent work in the non-global case?
